image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
# DOCKER_HOST: tcp://localhost:2375

services:
  - docker:dind

stages:
  - generate
  - build
  - deploy

generate:
  image:
    name: alpine:latest
  stage: generate
  only:
    - master
  script:
    - export VERSION=0.62.1
    - apk add --no-cache git openssl py-pygments curl
    - curl -L https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz | tar -xz
    - mv hugo /usr/local/bin/hugo
    - apk del curl
    - /usr/local/bin/hugo
  artifacts:
    paths:
      - public
    expire_in: 30 days

build:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.serial-experiments.com
    - docker build -t registry.serial-experiments.com/${CI_PROJECT_PATH}:latest .
    - docker push registry.serial-experiments.com/${CI_PROJECT_PATH}:latest

build_tagged:
  stage: build
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.serial-experiments.com
    - docker build -t registry.serial-experiments.com/$CI_PROJECT_PATH:$CI_COMMIT_TAG .
    - docker push registry.serial-experiments.com/$CI_PROJECT_PATH:$CI_COMMIT_TAG

deploy:
  image: registry.serial-experiments.com/bart/exoframe:latest
  stage: deploy
  only:
    - master
  script:
    - exoframe endpoint https://exoframe.serial-experiments.com
    - exoframe deploy -t eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbiI6dHJ1ZSwidXNlciI6eyJ1c2VybmFtZSI6ImFlb2x1biJ9LCJ0b2tlbk5hbWUiOiJnaXRsYWIiLCJkZXBsb3kiOnRydWUsImlhdCI6MTU1NjYyOTc0NX0.V48qwiw1vLPiKcHEE2mMOjGw_lgdloKIQZQHzfKBNSI
