version: "3"
services:
  app:
    image: registry.serial-experiments.com/bart/serial-experiments.com:latest
    restart: always
    environment:
      NODE_ENV: production
    labels:
      traefik.http.routers.serex.rule: 'Host(`serial-experiments.com`)'
      traefik.http.services.serex.loadbalancer.server.port: 80
